version: '3.8'

services:
  mcp-gateway:
    image: docker/mcp-gateway:latest
    container_name: mcp-gateway
    restart: unless-stopped
    command:
      - --transport=sse
      - --port=3333
      - --catalog=docker-mcp.yaml
      - --catalog=rg-mcp.yaml
      - --servers=brave,clickup,desktop-commander,dockerhub,exa,fetch,filesystem,git,markdownify,memory,openbnb-airbnb,perplexity-ask,playwright,playwright-mcp-server,puppeteer,resend,sequentialthinking,task-orchestrator
      - --verbose
      - --block-secrets=false
    ports:
      - "3333:3333"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERPROFILE}/.docker/mcp:/root/.docker/mcp:ro
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
    networks:
      - mcp-network

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mcp-cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/docker-config.yml run
    volumes:
      - ${USERPROFILE}/.cloudflared:/etc/cloudflared:ro
    depends_on:
      - mcp-gateway
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
