version: 2
name: production-verified
displayName: Production Verified MCP Servers
registry:
  brave-search:
    description: Search the Web for pages, images, news, videos, and more using the Brave Search API.
    title: Brave Search
    type: server
    dateAdded: "2025-10-18T00:00:00Z"
    image: mcp/brave-search@sha256:85776817ada6c0b7a2681afcb0877fbb17c62fd0299a4be606614eb1e2c2ffca
    ref: ""
    readme: http://desktop.docker.com/mcp/catalog/v2/readme/brave.md
    toolsUrl: http://desktop.docker.com/mcp/catalog/v2/tools/brave.json
    source: https://github.com/brave/brave-search-mcp-server/tree/main
    upstream: https://github.com/brave/brave-search-mcp-server
    icon: https://avatars.githubusercontent.com/u/12301619?s=200&v=4
    tools:
      - name: brave_image_search
      - name: brave_local_search
      - name: brave_news_search
      - name: brave_summarizer
      - name: brave_video_search
      - name: brave_web_search
    secrets:
      - name: brave.api_key
        env: BRAVE_API_KEY
        example: YOUR_API_KEY_HERE
    env:
      - name: BRAVE_MCP_TRANSPORT
        value: stdio
    prompts: 0
    resources: {}
    metadata:
      category: search
      tags:
        - brave
        - search
      license: MIT License
      owner: brave

  wikipedia:
    description: Search and retrieve Wikipedia articles
    title: Wikipedia
    type: server
    dateAdded: "2025-10-18T00:00:00Z"
    image: mcp/wikipedia@sha256:ec13ce7fd0d1e1b72e12a5f23e3bf54bc38af00cce7ad2c28ef30de9f29821ad
    ref: ""
    source: https://github.com/modelcontextprotocol/servers/tree/main/src/wikipedia
    upstream: https://github.com/modelcontextprotocol/servers
    tools:
      - name: wikipedia_search
      - name: wikipedia_get_article
    env:
      - name: MCP_TRANSPORT
        value: stdio
    prompts: 0
    resources: {}
    metadata:
      category: search
      tags:
        - wikipedia
        - search
      license: MIT License

  time:
    description: Time and timezone conversion utilities
    title: Time Utilities
    type: server
    dateAdded: "2025-10-18T00:00:00Z"
    image: mcp/time@sha256:4e0cb0e95f9e37e7e16ba17f8cd7bd5f5f3e8d8c04a7c8f76a1e11e9e4b79e74
    ref: ""
    source: https://github.com/modelcontextprotocol/servers/tree/main/src/time
    upstream: https://github.com/modelcontextprotocol/servers
    tools:
      - name: get_current_time
      - name: convert_timezone
    env:
      - name: MCP_TRANSPORT
        value: stdio
    prompts: 0
    resources: {}
    metadata:
      category: utilities
      tags:
        - time
        - utilities

  github:
    description: GitHub repository management and operations
    title: GitHub
    type: server
    dateAdded: "2025-10-18T00:00:00Z"
    image: mcp/github@sha256:a9c0b38ec30e4e9563a4b84f36a5f1e93cfe24f93e6b8e99d2da3f50e8c7d4a1
    ref: ""
    source: https://github.com/modelcontextprotocol/servers/tree/main/src/github
    upstream: https://github.com/modelcontextprotocol/servers
    tools:
      - name: create_repository
      - name: get_file_contents
      - name: push_files
      - name: create_issue
      - name: create_pull_request
      - name: fork_repository
      - name: create_branch
    secrets:
      - name: github.personal_access_token
        env: GITHUB_PERSONAL_ACCESS_TOKEN
        example: ghp_your_token_here
    env:
      - name: MCP_TRANSPORT
        value: stdio
    prompts: 0
    resources: {}
    metadata:
      category: devops
      tags:
        - github
        - git
        - devops
      license: MIT License
